### ISSUE TITLE
Rework inverter EEPROM read/write to fit with CAN Rx dispatch thread

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#102]
### Description
New CAN receive dispatch thread will break the success checks in `pm100_eeprom_<read/write>_blocking()` functions.

### Tasks
- [ ] Create a new system initialisation thread.
- [ ] Disable auto-starting of threads other than the CAN Rx dispatch thread.
- [ ] Write EEPROM parameters from this thread (CAN Rx dispatch service will be running).
- [ ] Move ready-to-drive to this new thread (after EEPROM write).
- [ ] Start other threads from this thread after ready-to-drive finished.
- [ ] Terminate this thread and release its resources.

### Additional context
Probably relies on:
#97  
#101

**Comment by t-bre** [comment]
EEPROM will no longer be set by the VCU but by the inverter configuration desktop app. Closing.
