### ISSUE TITLE
refactor(rtos): initialisation thread

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#121]
### Description
Move the initialisation and ready-to-drive wait process to a thread, rather than before the RTOS begins.

### Tasks
- [x] Create function for pre-RTOS kernel entry initialisation (creating threads / RTOS services etc) and move related initialisation to this function.
- [x] Create initialisation thread which auto-starts.
- [x] Prevent other threads from auto-starting (except the CAN Rx thread).
- [x] Move existing initialisation functions to this new thread.
- [x] Start remaining threads and terminate the initialisation thread once initialisation finishes.

### Additional context
Related / affects: 
#120 
#119
