### ISSUE TITLE
feat(apps): upper and lower bounds check on ADC readings

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#132]
### Description
Check that the raw APPS ADC readings are not too far above or below the expected bounds.

### Tasks
- [ ] Implement bounds check.
- [ ] Enter fault state if bounds exceeded.
- [ ] Add configuration parameter for percentage above/below bounds to cause fault.

### Additional context
Rough sketch of behaviour:
<img width="512" alt="APPS Input" src="https://user-images.githubusercontent.com/31595761/176942086-fa854cc0-afc3-4c49-a15d-51f1f6b0e93d.png">
