### ISSUE TITLE
refactor(apps): update APPS to use new SCS interface

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#139]
### Description
Update APPS functions to use new SCS interface.

### Tasks
- [ ] Define new SCS instances for each APPS signal.
- [ ] Read APPS signals through new SCS interface.
- [ ] Validate APPS signals through new SCS interface.
