### ISSUE TITLE
refactor!: restructure directories

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#149]
### Description
Various changes to directory structure.

### Tasks
- [x] Rename `embedded` to `src`.
- [x] Move `embedded/Scripts` to `scripts`
- [x] Move makefile to repo root.

### Additional Notes
Make sure to use `git mv`.
