### ISSUE TITLE
feat(mcu): make use of TCM RAM

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#151]
### Description
ARM Cortex M7 cores include "Tightly Coupled Memory" (TCM) RAM which is fast memory very close to the CPU. This could 

### Tasks
- [ ] Investigate possible areas for use of TCM RAM for performance boost.
- [ ] Work out how to place data/instructions in TCM RAM.
- [ ] Move data/instructions into TCM RAM.

### Relevant FSUK Rules
N/A

### Additional Notes
- Probably can place things in TCM via compiler attributes.
- RTOS code and thread stacks probably good to be put in TCM.
