### ISSUE TITLE
feat(safety): system critical signal interface

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#74]
### Description
There is no system for reading and checking system critical signals at the moment. In the VCU this relates to the ADC inputs from the throttle pedal. It would be useful to define a data structure and wrapper functions around the ADC HAL for working with safety critical signals.

### Tasks
- [x] `struct` to represent a safety critical signal with a simple method of defining new signals.
- [x] Wrapper function around the ADC HAL to read signal.
- [x] Validation function to ensure signal within bounds.

### Relevant FSUK Rules
**T11.9** &nbsp; System critical signals (entire section).
