### ISSUE TITLE
feat(io): pin assignments and configuration

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu#78]
### Description
Any pins we might need to be broken out in future should be reserved ahead of time.

### Tasks
- [x] Shutdown in (L).
- [x] Ready to drive in (H).
- [x] Ready to drive out (L).
- [x] Buzzer out (H).
- [x] BPS ADC pin.

H: active high
L: active low

### Additional Notes
Ready to drive out can be used as inverter enable (inverted).

**Comment by t-bre** [comment]
@lebedys @maxobrien Is this the correct sequence for these pins and the VCU state?

![VCU Timing](https://user-images.githubusercontent.com/31595761/169662636-70a90af9-e23d-45c0-8fc4-1f32962dbcf3.svg)

**Comment by t-bre** [comment]
Pin assignments done and tested.
